Repository JJHHYB/deepvalley-back, pull requests merged in 2024-08, with the labels that each got.

#94 feat: 지역 검색 기능 추가
  src/main/java/jjhhyb/deepvalley/config/SecurityConfig.java
  src/main/java/jjhhyb/deepvalley/place/region/Region.java
  src/main/java/jjhhyb/deepvalley/place/region/RegionController.java
  src/main/java/jjhhyb/deepvalley/place/region/RegionRepository.java
  src/main/java/jjhhyb/deepvalley/place/region/RegionService.java
  src/main/java/jjhhyb/deepvalley/place/region/dto/RegionListResponse.java
  src/main/java/jjhhyb/deepvalley/place/valley/ValleyController.java
  src/main/java/jjhhyb/deepvalley/place/valley/ValleyService.java
  src/main/java/jjhhyb/deepvalley/place/valley/repository/CustomizedValleyRepository.java
  src/main/java/jjhhyb/deepvalley/place/valley/repository/CustomizedValleyRepositoryImpl.java
  src/test/java/jjhhyb/deepvalley/place/RegionIntegrationTests.java
Labels: feat✅

#96 hotfix: 우편번호 타입 문자열로 변경
  src/main/java/jjhhyb/deepvalley/place/Place.java
  src/main/java/jjhhyb/deepvalley/place/valley/dto/ValleyDetailResponse.java
  src/main/java/jjhhyb/deepvalley/place/valley/dto/ValleyQueryDTO.java
  src/test/java/jjhhyb/deepvalley/place/PlaceMapperTests.java
Labels: fix🚑

#97 추천 계곡 api
  src/main/java/jjhhyb/deepvalley/community/ReviewController.java
  src/main/java/jjhhyb/deepvalley/community/dto/response/PlaceImageResponse.java
  src/main/java/jjhhyb/deepvalley/community/entity/ReviewImage.java
  src/main/java/jjhhyb/deepvalley/community/repository/ImageRepository.java
  src/main/java/jjhhyb/deepvalley/community/repository/ReviewRepository.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewImageService.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewService.java
  src/main/java/jjhhyb/deepvalley/image/Image.java
  src/main/java/jjhhyb/deepvalley/recommend/RecommendController.java
  src/main/java/jjhhyb/deepvalley/recommend/RecommendService.java
  src/main/java/jjhhyb/deepvalley/recommend/dto/response/RecommendResponse.java
  src/test/java/jjhhyb/deepvalley/community/ReviewServiceTest.java
  src/test/java/jjhhyb/deepvalley/recommend/RecommendServiceTest.java
  src/test/java/jjhhyb/deepvalley/testObject/TestObjectPlace.java
Labels: feat✅

#99 Develop -> Main 배포
  src/main/java/jjhhyb/deepvalley/community/ReviewController.java
  src/main/java/jjhhyb/deepvalley/community/dto/response/PlaceImageResponse.java
  src/main/java/jjhhyb/deepvalley/community/dto/response/ReviewDetailResponse.java
  src/main/java/jjhhyb/deepvalley/community/entity/ReviewImage.java
  src/main/java/jjhhyb/deepvalley/community/repository/ImageRepository.java
  src/main/java/jjhhyb/deepvalley/community/repository/ReviewRepository.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewImageService.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewService.java
  src/main/java/jjhhyb/deepvalley/config/SecurityConfig.java
  src/main/java/jjhhyb/deepvalley/image/Image.java
  src/main/java/jjhhyb/deepvalley/place/Place.java
  src/main/java/jjhhyb/deepvalley/place/region/Region.java
  src/main/java/jjhhyb/deepvalley/place/region/RegionController.java
  src/main/java/jjhhyb/deepvalley/place/region/RegionRepository.java
  src/main/java/jjhhyb/deepvalley/place/region/RegionService.java
  src/main/java/jjhhyb/deepvalley/place/region/dto/RegionListResponse.java
  src/main/java/jjhhyb/deepvalley/place/valley/Valley.java
  src/main/java/jjhhyb/deepvalley/place/valley/ValleyController.java
  src/main/java/jjhhyb/deepvalley/place/valley/ValleyService.java
  src/main/java/jjhhyb/deepvalley/place/valley/dto/ValleyDetailResponse.java
  src/main/java/jjhhyb/deepvalley/place/valley/dto/ValleyQueryDTO.java
  src/main/java/jjhhyb/deepvalley/place/valley/repository/CustomizedValleyRepository.java
  src/main/java/jjhhyb/deepvalley/place/valley/repository/CustomizedValleyRepositoryImpl.java
  src/main/java/jjhhyb/deepvalley/place/valley/repository/ValleyRepository.java
  src/main/java/jjhhyb/deepvalley/recommend/RecommendController.java
  src/main/java/jjhhyb/deepvalley/recommend/RecommendService.java
  src/main/java/jjhhyb/deepvalley/recommend/dto/response/RecommendResponse.java
  src/main/java/jjhhyb/deepvalley/user/controller/MemberController.java
  src/test/java/jjhhyb/deepvalley/community/ReviewServiceTest.java
  src/test/java/jjhhyb/deepvalley/place/FacilityIntegrationTests.java
  src/test/java/jjhhyb/deepvalley/place/PlaceMapperTests.java
  src/test/java/jjhhyb/deepvalley/place/RegionIntegrationTests.java
  src/test/java/jjhhyb/deepvalley/place/ValleyIntegrationTests.java
  src/test/java/jjhhyb/deepvalley/recommend/RecommendServiceTest.java
  src/test/java/jjhhyb/deepvalley/testObject/TestObjectPlace.java
Labels: update✨

#100 deploy log 추가
  .github/workflows/main.yml
  scripts/deploy.sh
Labels: fix🚑, feat✅

#103 SECRET_FILE 절대경로 추가
  scripts/deploy.sh
Labels: fix🚑

#104 SECRET_FILE 경로 수정
  .github/workflows/main.yml
  scripts/deploy.sh
Labels: fix🚑

#105 배포 로그 기록 삭제
  .github/workflows/main.yml
  scripts/deploy.sh
Labels: fix🚑

#106 디버그 모드로 실행
  scripts/deploy.sh
Labels: fix🚑

#107 응답 값에 Boolean 값 제거
  src/main/java/jjhhyb/deepvalley/place/valley/Valley.java
Labels: feat✅

#108 pwd 추가
  scripts/deploy.sh
Labels: feat✅

#109 Spring Boot 실행 로그 추가
  scripts/deploy.sh
Labels: feat✅

#110 Spring Boot 실행 로그 삭제
  scripts/deploy.sh
Labels: fix🚑

#111 jar 파일 확인하기
  scripts/deploy.sh
Labels: fix🚑

#112 jar 절대 경로 추가
  scripts/deploy.sh
Labels: fix🚑

#116 place 에 업데이트 되는 부분 수정
  src/main/java/jjhhyb/deepvalley/community/service/ReviewService.java
  src/main/java/jjhhyb/deepvalley/place/Place.java
  src/main/java/jjhhyb/deepvalley/place/PlaceRepository.java
Labels: feat✅

#118 feat: 아이디/비밀번호 찾기
  src/main/java/jjhhyb/deepvalley/config/SecurityConfig.java
  src/main/java/jjhhyb/deepvalley/user/controller/KakaoLoginController.java
  src/main/java/jjhhyb/deepvalley/user/controller/MemberController.java
  src/main/java/jjhhyb/deepvalley/user/dto/FindIdRequestDto.java
  src/main/java/jjhhyb/deepvalley/user/dto/FindIdResponseDto.java
  src/main/java/jjhhyb/deepvalley/user/dto/FindPasswordRequestDto.java
  src/main/java/jjhhyb/deepvalley/user/dto/FindPasswordResponseDto.java
  src/main/java/jjhhyb/deepvalley/user/dto/ProfileResponseDto.java
  src/main/java/jjhhyb/deepvalley/user/entity/Member.java
  src/main/java/jjhhyb/deepvalley/user/repository/MemberRepository.java
  src/main/java/jjhhyb/deepvalley/user/service/KakaoLoginService.java
  src/main/java/jjhhyb/deepvalley/user/service/MemberService.java
Labels: feat✅

#119 feat: Add Suggest API
  app.log
  src/main/java/jjhhyb/deepvalley/image/ImageService.java
  src/main/java/jjhhyb/deepvalley/image/ImageType.java
  src/main/java/jjhhyb/deepvalley/suggest/Suggest.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestController.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestDetailResponse.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestImage.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestImageId.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestImageRepository.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestImageService.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestNotFoundException.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestPostRequest.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestRepository.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestService.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestsResponse.java
Labels: feat✅

#120 feat: Add Suggest API (#119)
  app.log
  src/main/java/jjhhyb/deepvalley/image/ImageService.java
  src/main/java/jjhhyb/deepvalley/image/ImageType.java
  src/main/java/jjhhyb/deepvalley/suggest/Suggest.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestController.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestDetailResponse.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestImage.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestImageId.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestImageRepository.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestImageService.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestNotFoundException.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestPostRequest.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestRepository.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestService.java
  src/main/java/jjhhyb/deepvalley/suggest/SuggestsResponse.java
Labels: feat✅

#121 feat: Add default thumbnail to valley
  src/main/java/jjhhyb/deepvalley/place/valley/dto/ValleyResponse.java
Labels: feat✅

#123 feat: Add sorting to valley search
  src/main/java/jjhhyb/deepvalley/config/WebConfig.java
  src/main/java/jjhhyb/deepvalley/place/PlaceSortType.java
  src/main/java/jjhhyb/deepvalley/place/StringToPlaceSortTypeConverter.java
  src/main/java/jjhhyb/deepvalley/place/exception/PlaceExceptionHandler.java
  src/main/java/jjhhyb/deepvalley/place/valley/ValleyController.java
  src/main/java/jjhhyb/deepvalley/place/valley/ValleyService.java
  src/main/java/jjhhyb/deepvalley/place/valley/repository/CustomizedValleyRepository.java
  src/main/java/jjhhyb/deepvalley/place/valley/repository/CustomizedValleyRepositoryImpl.java
Labels: feat✅

#125 Fix : 리뷰 업데이트 사진 업로드 부분 로직 수정
  src/main/java/jjhhyb/deepvalley/community/service/ReviewService.java
Labels: fix🚑
