Repository JJHHYB/deepvalley-back, pull requests merged in 2024-07, with the labels that each got.

#2 Project Setting
  .github/CODEOWNERS
  .github/pull_request_template.md
  .gitignore
Labels: docs📝

#4 develop 브랜치 생성
  README.md
Labels: docs📝

#5 CICD 구축
  .github/workflows/main.yml
  appspec.yml
  build.gradle
  deploy.sh
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/jjhhyb/deepvalley/DeepvalleyApplication.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/test/java/jjhhyb/deepvalley/DeepvalleyApplicationTests.java
Labels: feat✅

#6 cicd test
  .github/workflows/main.yml
  appspec.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  scripts/deploy.sh
  settings.gradle
  src/main/java/jjhhyb/deepvalley/DeepvalleyApplication.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/test/java/jjhhyb/deepvalley/DeepvalleyApplicationTests.java
Labels: test🏷️

#7 cicd : 배포 test
  src/main/java/jjhhyb/deepvalley/DeepvalleyApplication.java
Labels: test🏷️

#27 cicd : 적용 브랜치 변경 및 빌드 파일 수정
  .github/workflows/main.yml
  scripts/deploy.sh
Labels: refactor♻️

#28 cicd 적용
  .github/workflows/main.yml
  scripts/deploy.sh
Labels: refactor♻️

#31 community entity
  .gitignore
  src/main/java/jjhhyb/deepvalley/community/dto/ReviewDto.java
  src/main/java/jjhhyb/deepvalley/community/entity/Image.java
  src/main/java/jjhhyb/deepvalley/community/entity/Review.java
  src/main/java/jjhhyb/deepvalley/community/entity/ReviewImage.java
  src/main/java/jjhhyb/deepvalley/community/entity/ReviewPrivacy.java
  src/main/java/jjhhyb/deepvalley/community/entity/ReviewRate.java
  src/main/java/jjhhyb/deepvalley/entityId/BaseId.java
  src/main/java/jjhhyb/deepvalley/entityId/PlaceTagId.java
  src/main/java/jjhhyb/deepvalley/entityId/ReviewImageId.java
  src/main/java/jjhhyb/deepvalley/entityId/ReviewTagId.java
  src/main/java/jjhhyb/deepvalley/tag/entity/PlaceTag.java
  src/main/java/jjhhyb/deepvalley/tag/entity/ReviewTag.java
  src/main/java/jjhhyb/deepvalley/tag/entity/Tag.java
Labels: feat✅

#32 tag, place entity 연관관계 부분 수정
  src/main/java/jjhhyb/deepvalley/community/entity/Review.java
  src/main/java/jjhhyb/deepvalley/place/Place.java
  src/main/java/jjhhyb/deepvalley/tag/entity/PlaceTag.java
Labels: refactor♻️

#33 Feat/member: 로그인, 회원가입, 내정보 구현
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/jpa.xml
  .idea/material_theme_project_new.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/deepvalley.main.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  build.gradle
  src/main/java/jjhhyb/deepvalley/config/SecurityConfig.java
  src/main/java/jjhhyb/deepvalley/user/auth/CustomUserDetails.java
  src/main/java/jjhhyb/deepvalley/user/auth/JWTFilter.java
  src/main/java/jjhhyb/deepvalley/user/auth/JWTUtil.java
  src/main/java/jjhhyb/deepvalley/user/auth/LoginFilter.java
  src/main/java/jjhhyb/deepvalley/user/controller/MemberController.java
  src/main/java/jjhhyb/deepvalley/user/dto/LoginRequestDto.java
  src/main/java/jjhhyb/deepvalley/user/dto/LoginResponseDto.java
  src/main/java/jjhhyb/deepvalley/user/dto/PasswordRequestDto.java
  src/main/java/jjhhyb/deepvalley/user/dto/ProfileRequestDto.java
  src/main/java/jjhhyb/deepvalley/user/dto/ProfileResponseDto.java
  src/main/java/jjhhyb/deepvalley/user/dto/RegisterRequestDto.java
  src/main/java/jjhhyb/deepvalley/user/dto/RegisterResponseDto.java
  src/main/java/jjhhyb/deepvalley/user/entity/Member.java
  src/main/java/jjhhyb/deepvalley/user/exception/GlobalExceptionHandler.java
  src/main/java/jjhhyb/deepvalley/user/exception/LoginException.java
  src/main/java/jjhhyb/deepvalley/user/exception/MyProfileException.java
  src/main/java/jjhhyb/deepvalley/user/exception/RegisterException.java
  src/main/java/jjhhyb/deepvalley/user/repository/MemberRepository.java
  src/main/java/jjhhyb/deepvalley/user/service/MemberService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.properties.bak
  src/main/resources/application.yml
  src/test/java/jjhhyb/deepvalley/user/service/MemberServiceTest.java
Labels: feat✅

#35 entity 수정
  src/main/java/jjhhyb/deepvalley/community/ReviewRepository.java
  src/main/java/jjhhyb/deepvalley/community/ReviewService.java
  src/main/java/jjhhyb/deepvalley/community/dto/ReviewDto.java
  src/main/java/jjhhyb/deepvalley/community/dto/request/ReviewPostRequest.java
  src/main/java/jjhhyb/deepvalley/community/dto/request/ReviewUpdateRequest.java
  src/main/java/jjhhyb/deepvalley/community/dto/response/ReviewDetailResponse.java
  src/main/java/jjhhyb/deepvalley/community/dto/response/ReviewsResponse.java
  src/main/java/jjhhyb/deepvalley/community/entity/Image.java
  src/main/java/jjhhyb/deepvalley/community/entity/Review.java
  src/main/java/jjhhyb/deepvalley/community/entity/ReviewImage.java
  src/main/java/jjhhyb/deepvalley/community/entity/ReviewRate.java
  src/main/java/jjhhyb/deepvalley/community/entity/ReviewRating.java
  src/main/java/jjhhyb/deepvalley/entityId/BaseId.java
  src/main/java/jjhhyb/deepvalley/entityId/PlaceTagId.java
  src/main/java/jjhhyb/deepvalley/entityId/ReviewImageId.java
  src/main/java/jjhhyb/deepvalley/entityId/ReviewTagId.java
  src/main/java/jjhhyb/deepvalley/place/Place.java
  src/main/java/jjhhyb/deepvalley/place/valley/Valley.java
  src/main/java/jjhhyb/deepvalley/tag/entity/PlaceTag.java
  src/main/java/jjhhyb/deepvalley/tag/entity/ReviewTag.java
  src/main/java/jjhhyb/deepvalley/tag/entity/Tag.java
  src/test/java/jjhhyb/deepvalley/community/service/ReviewServiceTest.java
Labels: fix🚑

#36 Main branch Merge(fix community entity)
  src/main/java/jjhhyb/deepvalley/community/ReviewRepository.java
  src/main/java/jjhhyb/deepvalley/community/ReviewService.java
  src/main/java/jjhhyb/deepvalley/community/dto/ReviewDto.java
  src/main/java/jjhhyb/deepvalley/community/dto/request/ReviewPostRequest.java
  src/main/java/jjhhyb/deepvalley/community/dto/request/ReviewUpdateRequest.java
  src/main/java/jjhhyb/deepvalley/community/dto/response/ReviewDetailResponse.java
  src/main/java/jjhhyb/deepvalley/community/dto/response/ReviewsResponse.java
  src/main/java/jjhhyb/deepvalley/community/entity/Image.java
  src/main/java/jjhhyb/deepvalley/community/entity/Review.java
  src/main/java/jjhhyb/deepvalley/community/entity/ReviewImage.java
  src/main/java/jjhhyb/deepvalley/community/entity/ReviewRate.java
  src/main/java/jjhhyb/deepvalley/community/entity/ReviewRating.java
  src/main/java/jjhhyb/deepvalley/entityId/BaseId.java
  src/main/java/jjhhyb/deepvalley/entityId/PlaceTagId.java
  src/main/java/jjhhyb/deepvalley/entityId/ReviewImageId.java
  src/main/java/jjhhyb/deepvalley/entityId/ReviewTagId.java
  src/main/java/jjhhyb/deepvalley/place/Place.java
  src/main/java/jjhhyb/deepvalley/place/valley/Valley.java
  src/main/java/jjhhyb/deepvalley/tag/entity/PlaceTag.java
  src/main/java/jjhhyb/deepvalley/tag/entity/ReviewTag.java
  src/main/java/jjhhyb/deepvalley/tag/entity/Tag.java
  src/test/java/jjhhyb/deepvalley/community/service/ReviewServiceTest.java
Labels: fix🚑

#37 fix: CORS issue
  src/main/java/jjhhyb/deepvalley/config/WebConfig.java
Labels: fix🚑

#38 fix: Add CORS filter
  src/main/java/jjhhyb/deepvalley/config/SecurityConfig.java
Labels: fix🚑

#39 리뷰 작성하기, 업데이트, 삭제, 조회
  src/main/java/jjhhyb/deepvalley/community/ReviewController.java
  src/main/java/jjhhyb/deepvalley/community/ReviewNotFoundException.java
  src/main/java/jjhhyb/deepvalley/community/ReviewRepository.java
  src/main/java/jjhhyb/deepvalley/community/ReviewService.java
  src/main/java/jjhhyb/deepvalley/community/dto/request/ReviewPostRequest.java
  src/main/java/jjhhyb/deepvalley/community/dto/request/ReviewUpdateRequest.java
  src/main/java/jjhhyb/deepvalley/community/dto/response/PlaceImageResponse.java
  src/main/java/jjhhyb/deepvalley/community/dto/response/ReviewDetailResponse.java
  src/main/java/jjhhyb/deepvalley/community/dto/response/ReviewsResponse.java
  src/main/java/jjhhyb/deepvalley/community/entity/Image.java
  src/main/java/jjhhyb/deepvalley/community/entity/Review.java
  src/main/java/jjhhyb/deepvalley/community/entity/ReviewImage.java
  src/main/java/jjhhyb/deepvalley/community/repository/ImageRepository.java
  src/main/java/jjhhyb/deepvalley/community/repository/ReviewImageRepository.java
  src/main/java/jjhhyb/deepvalley/community/repository/ReviewRepository.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewImageService.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewService.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewTagService.java
  src/main/java/jjhhyb/deepvalley/config/WebConfig.java
  src/main/java/jjhhyb/deepvalley/entityId/ReviewImageId.java
  src/main/java/jjhhyb/deepvalley/entityId/ReviewTagId.java
  src/main/java/jjhhyb/deepvalley/place/Place.java
  src/main/java/jjhhyb/deepvalley/place/PlaceRepository.java
  src/main/java/jjhhyb/deepvalley/place/valley/Valley.java
  src/main/java/jjhhyb/deepvalley/place/valley/ValleyRepository.java
  src/main/java/jjhhyb/deepvalley/tag/ReviewTagRepository.java
  src/main/java/jjhhyb/deepvalley/tag/TagRepository.java
  src/main/java/jjhhyb/deepvalley/tag/entity/ReviewTag.java
  src/main/java/jjhhyb/deepvalley/tag/entity/Tag.java
  src/main/java/jjhhyb/deepvalley/user/entity/Member.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/jjhhyb/deepvalley/community/ReviewServiceTest.java
  src/test/java/jjhhyb/deepvalley/community/service/ReviewServiceTest.java
Labels: feat✅

#41 Main branch Merge(리뷰 작성하기, 업데이트, 삭제하기, 조회하기)
  src/main/java/jjhhyb/deepvalley/community/ReviewController.java
  src/main/java/jjhhyb/deepvalley/community/ReviewNotFoundException.java
  src/main/java/jjhhyb/deepvalley/community/ReviewRepository.java
  src/main/java/jjhhyb/deepvalley/community/ReviewService.java
  src/main/java/jjhhyb/deepvalley/community/dto/request/ReviewPostRequest.java
  src/main/java/jjhhyb/deepvalley/community/dto/request/ReviewUpdateRequest.java
  src/main/java/jjhhyb/deepvalley/community/dto/response/PlaceImageResponse.java
  src/main/java/jjhhyb/deepvalley/community/dto/response/ReviewDetailResponse.java
  src/main/java/jjhhyb/deepvalley/community/dto/response/ReviewsResponse.java
  src/main/java/jjhhyb/deepvalley/community/entity/Image.java
  src/main/java/jjhhyb/deepvalley/community/entity/Review.java
  src/main/java/jjhhyb/deepvalley/community/entity/ReviewImage.java
  src/main/java/jjhhyb/deepvalley/community/repository/ImageRepository.java
  src/main/java/jjhhyb/deepvalley/community/repository/ReviewImageRepository.java
  src/main/java/jjhhyb/deepvalley/community/repository/ReviewRepository.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewImageService.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewService.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewTagService.java
  src/main/java/jjhhyb/deepvalley/config/WebConfig.java
  src/main/java/jjhhyb/deepvalley/entityId/ReviewImageId.java
  src/main/java/jjhhyb/deepvalley/entityId/ReviewTagId.java
  src/main/java/jjhhyb/deepvalley/place/Place.java
  src/main/java/jjhhyb/deepvalley/place/PlaceRepository.java
  src/main/java/jjhhyb/deepvalley/place/valley/Valley.java
  src/main/java/jjhhyb/deepvalley/place/valley/ValleyRepository.java
  src/main/java/jjhhyb/deepvalley/tag/ReviewTagRepository.java
  src/main/java/jjhhyb/deepvalley/tag/TagRepository.java
  src/main/java/jjhhyb/deepvalley/tag/entity/ReviewTag.java
  src/main/java/jjhhyb/deepvalley/tag/entity/Tag.java
  src/main/java/jjhhyb/deepvalley/user/entity/Member.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/jjhhyb/deepvalley/community/ReviewServiceTest.java
  src/test/java/jjhhyb/deepvalley/community/service/ReviewServiceTest.java
Labels: update✨

#43 특정 유저의 리뷰 목록 조회 기능 및 테스트 코드 수정
  src/main/java/jjhhyb/deepvalley/community/ReviewController.java
  src/main/java/jjhhyb/deepvalley/community/repository/ReviewRepository.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewService.java
  src/main/resources/application.yml
  src/test/java/jjhhyb/deepvalley/community/ReviewServiceTest.java
Labels: feat✅

#46 feat: 소셜 로그인(카카오) 기능 구현
  build.gradle
  src/main/java/jjhhyb/deepvalley/config/ClientConfig.java
  src/main/java/jjhhyb/deepvalley/config/SecurityConfig.java
  src/main/java/jjhhyb/deepvalley/user/controller/KakaoLoginController.java
  src/main/java/jjhhyb/deepvalley/user/controller/MemberController.java
  src/main/java/jjhhyb/deepvalley/user/jwt/CustomUserDetails.java
  src/main/java/jjhhyb/deepvalley/user/jwt/JWTFilter.java
  src/main/java/jjhhyb/deepvalley/user/jwt/JWTUtil.java
  src/main/java/jjhhyb/deepvalley/user/jwt/LoginFilter.java
  src/main/java/jjhhyb/deepvalley/user/oauth/provider/kakao/KakaoAuthDto.java
  src/main/java/jjhhyb/deepvalley/user/oauth/provider/kakao/KakaoTokenDto.java
  src/main/java/jjhhyb/deepvalley/user/oauth/provider/kakao/KakaoUserInfoDto.java
  src/main/java/jjhhyb/deepvalley/user/service/KakaoLoginService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties.bak
  src/main/resources/application.yml
Labels: feat✅

#47 소셜 로그인 테스트코드 추가 / HTTPS 설정
  src/main/java/jjhhyb/deepvalley/user/service/KakaoLoginService.java
  src/main/resources/application.yml
  src/main/resources/keystore.p12
  src/test/java/jjhhyb/deepvalley/user/service/KakaoLoginServiceTest.java
Labels: chore👷, test🏷️

#48 DevelopMain branch Merge(리뷰 목록, 카카오 로그인)
  build.gradle
  src/main/java/jjhhyb/deepvalley/community/ReviewController.java
  src/main/java/jjhhyb/deepvalley/community/repository/ReviewRepository.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewService.java
  src/main/java/jjhhyb/deepvalley/config/ClientConfig.java
  src/main/java/jjhhyb/deepvalley/config/SecurityConfig.java
  src/main/java/jjhhyb/deepvalley/user/controller/KakaoLoginController.java
  src/main/java/jjhhyb/deepvalley/user/controller/MemberController.java
  src/main/java/jjhhyb/deepvalley/user/jwt/CustomUserDetails.java
  src/main/java/jjhhyb/deepvalley/user/jwt/JWTFilter.java
  src/main/java/jjhhyb/deepvalley/user/jwt/JWTUtil.java
  src/main/java/jjhhyb/deepvalley/user/jwt/LoginFilter.java
  src/main/java/jjhhyb/deepvalley/user/oauth/provider/kakao/KakaoAuthDto.java
  src/main/java/jjhhyb/deepvalley/user/oauth/provider/kakao/KakaoTokenDto.java
  src/main/java/jjhhyb/deepvalley/user/oauth/provider/kakao/KakaoUserInfoDto.java
  src/main/java/jjhhyb/deepvalley/user/service/KakaoLoginService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties.bak
  src/main/resources/application.yml
  src/main/resources/keystore.p12
  src/test/java/jjhhyb/deepvalley/community/ReviewServiceTest.java
  src/test/java/jjhhyb/deepvalley/user/service/KakaoLoginServiceTest.java
Labels: update✨

#49 github action 최신코드 반영하기
  .github/workflows/main.yml
Labels: refactor♻️

#50 github action 코드 수정
  .github/workflows/main.yml
Labels: update✨

#51 배포 로그 기록 추가
  .github/workflows/main.yml
  scripts/deploy.sh
Labels: refactor♻️

#53 Feat: Swagger 적용
  build.gradle
  src/main/java/jjhhyb/deepvalley/config/SecurityConfig.java
  src/main/java/jjhhyb/deepvalley/config/SwaggerConfig.java
  src/main/java/jjhhyb/deepvalley/user/controller/KakaoLoginController.java
  src/main/java/jjhhyb/deepvalley/user/controller/MemberController.java
  src/main/resources/application.yml
  src/main/resources/keystore.p12
Labels: feat✅

#55 refactor: delete conflicted-library
  build.gradle
Labels: fix🚑

#57 config: Add server addres
  src/main/resources/application.yml
Labels: chore👷

#58 Main branch Merge(application.yml)
  src/main/resources/application.yml
Labels: chore👷

#59 Review controller swagger 적용
  src/main/java/jjhhyb/deepvalley/community/ReviewController.java
Labels: feat✅

#60 refactor: update password-change
  src/main/java/jjhhyb/deepvalley/user/controller/MemberController.java
  src/main/java/jjhhyb/deepvalley/user/dto/PasswordRequestDto.java
  src/main/java/jjhhyb/deepvalley/user/exception/GlobalExceptionHandler.java
  src/main/java/jjhhyb/deepvalley/user/exception/MyProfileException.java
  src/main/java/jjhhyb/deepvalley/user/service/MemberService.java
Labels: refactor♻️

#61 Main branch Merge(Update Password-Change)
  src/main/java/jjhhyb/deepvalley/community/ReviewController.java
  src/main/java/jjhhyb/deepvalley/user/controller/MemberController.java
  src/main/java/jjhhyb/deepvalley/user/dto/PasswordRequestDto.java
  src/main/java/jjhhyb/deepvalley/user/exception/GlobalExceptionHandler.java
  src/main/java/jjhhyb/deepvalley/user/exception/MyProfileException.java
  src/main/java/jjhhyb/deepvalley/user/service/MemberService.java
Labels: update✨

#62 이미지 s3 처리
  .github/workflows/main.yml
  build.gradle
  src/main/java/jjhhyb/deepvalley/community/ReviewController.java
  src/main/java/jjhhyb/deepvalley/community/dto/request/ReviewPostRequest.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewImageService.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewService.java
  src/main/java/jjhhyb/deepvalley/community/service/S3Service.java
  src/main/java/jjhhyb/deepvalley/config/S3Config.java
  src/main/resources/application.yml
  src/test/java/jjhhyb/deepvalley/community/ReviewServiceTest.java
Labels: feat✅

#65 fix : multipart.enabled 추가 controller 수정
  src/main/java/jjhhyb/deepvalley/community/ReviewController.java
  src/main/java/jjhhyb/deepvalley/community/dto/request/ReviewPostRequest.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewService.java
  src/main/resources/application.yml
  src/test/java/jjhhyb/deepvalley/community/ReviewServiceTest.java
Labels: fix🚑

#68 계곡 상세정보 API 버그 수정
  src/main/java/jjhhyb/deepvalley/place/valley/repository/ValleyRepository.java
Labels: fix🚑

#67 s3 403 error 수정
  build.gradle
Labels: fix🚑

#70 ${{}} 문법 적용
  src/main/resources/application.yml
Labels: fix🚑

#71 fix : ${} 수정
  src/main/resources/application.yml
Labels: fix🚑

#69 s3 버킷 403 error 해결
  .github/workflows/main.yml
  build.gradle
  scripts/deploy.sh
  src/main/java/jjhhyb/deepvalley/community/ReviewController.java
  src/main/java/jjhhyb/deepvalley/place/valley/ValleyController.java
  src/main/resources/application.yml
Labels: fix🚑, update✨

#72 code deploy 수정
  appspec.yml
  scripts/deploy.sh
  scripts/setup_permissions.sh
Labels: fix🚑

#75 chore: secrets 프로필 추가
  .gitignore
  src/main/resources/application.yml
Labels: chore👷

#76 image 처리 분리
  src/main/java/jjhhyb/deepvalley/community/repository/ImageRepository.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewImageService.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewService.java
  src/main/java/jjhhyb/deepvalley/image/ImageService.java
  src/main/java/jjhhyb/deepvalley/image/ImageType.java
  src/main/java/jjhhyb/deepvalley/image/S3Service.java
Labels: refactor♻️, feat✅

#74 docs: Add swagger annotation
  src/main/java/jjhhyb/deepvalley/place/facility/FacilityController.java
  src/main/java/jjhhyb/deepvalley/place/valley/ValleyController.java
Labels: docs📝

#82 deploy 오타 수정
  scripts/deploy.sh
Labels: chore👷

#83 Develop -> main
  scripts/deploy.sh
Labels: update✨

#86 feat: Add monitor library(prometheous)
  build.gradle
  src/main/java/jjhhyb/deepvalley/config/SecurityConfig.java
  src/main/java/jjhhyb/deepvalley/user/service/MemberService.java
Labels: feat✅

#87 Develop -> Main
  build.gradle
  src/main/java/jjhhyb/deepvalley/config/SecurityConfig.java
  src/main/java/jjhhyb/deepvalley/user/service/MemberService.java
Labels: update✨

#85 Feat: 프로필 이미지 저장
  app.log
  src/main/java/jjhhyb/deepvalley/community/service/ReviewImageService.java
  src/main/java/jjhhyb/deepvalley/user/controller/MemberController.java
  src/main/java/jjhhyb/deepvalley/user/service/MemberService.java
  src/test/java/jjhhyb/deepvalley/user/service/MemberServiceTest.java
Labels: feat✅

#89 Develop -> Main
  app.log
  src/main/java/jjhhyb/deepvalley/community/service/ReviewImageService.java
  src/main/java/jjhhyb/deepvalley/user/controller/MemberController.java
  src/main/java/jjhhyb/deepvalley/user/service/MemberService.java
  src/test/java/jjhhyb/deepvalley/user/service/MemberServiceTest.java
Labels: update✨

#90 리뷰 이미지가 없을 경우의 처리
  src/main/java/jjhhyb/deepvalley/community/ReviewController.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewService.java
Labels: feat✅

#91 Develop -> Main
  src/main/java/jjhhyb/deepvalley/community/ReviewController.java
  src/main/java/jjhhyb/deepvalley/community/repository/ReviewRepository.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewService.java
  src/main/java/jjhhyb/deepvalley/user/service/MemberService.java
Labels: update✨

#92 Test Code 및 코드 수정
  src/main/java/jjhhyb/deepvalley/community/dto/response/ReviewDetailResponse.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewService.java
  src/test/java/jjhhyb/deepvalley/community/ReviewServiceTest.java
  src/test/java/jjhhyb/deepvalley/testObject/TestObjectMember.java
  src/test/java/jjhhyb/deepvalley/testObject/TestObjectPlace.java
Labels: fix🚑, feat✅

#93 Develop -> main (Review)
  src/main/java/jjhhyb/deepvalley/community/dto/response/ReviewDetailResponse.java
  src/main/java/jjhhyb/deepvalley/community/service/ReviewService.java
  src/test/java/jjhhyb/deepvalley/community/ReviewServiceTest.java
  src/test/java/jjhhyb/deepvalley/testObject/TestObjectMember.java
  src/test/java/jjhhyb/deepvalley/testObject/TestObjectPlace.java
Labels: update✨
